# Generated by Django 5.2 on 2025-05-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
    ]
